### ISSUE TITLE
Allow overriding/specifying custom allocator/deallocator pair

### ISSUE THREAD

**Issue by legends2k** [Rabios/ice_libs#1]
Memory allocations directly use `malloc` and `free`.  Having a couple of macros like `ALLOC_FUNC` and `DEALLOC_FUNC` and using them everywhere would be better.  `malloc` and `free` can be defaults when these macros are undefined.  This would be beneficial for using these headers in projects that have tight memory constraints and do manual memory management.  Example: [stb](https://github.com/nothings/stb/blob/c9064e317699d2e495f36ba4f9ac037e88ee371a/stb_image.h#L648).

**Comment by Rabios** [comment]
Added custom memory allocation functions to libs that uses memory functions!
Thanks for being interested in ice_libs and opened this issue!
